### ISSUE TITLE
[FEATURE] more precise ITimeSource

### ISSUE THREAD

**Issue by Beyley** [Furball-Engine/Furball#21]
**Is your feature request related to a problem? Please describe.**
in pTyping, there are a lot of rounding errors for note position due to all ITimeSource's being integer based, meaning sometimes the position it should be at doesnt match what it actually is

**Describe the solution you'd like**
id like if ITimeSource returned a double for GetCurrentTime instead of an int

**Comment by Eeveelution** [comment]
sure i guess, although this will only if anything affect AudioTimeSource, GameTimeSource uses a Stopwatch which returns a long for milliseconds, instead of a double

**Comment by Beyley** [comment]
> sure i guess, although this will only if anything affect AudioTimeSource, GameTimeSource uses a Stopwatch which returns a long for milliseconds, instead of a double

you can do `_stopwatch.Elapsed.TotalMilliseconds` for the time as a double

**Comment by Eeveelution** [comment]
Tweens and ITimeSource are now on doubles instead of ints on the tween-time-precision branch
