### ISSUE TITLE
DrawableManagers stay in memory pernamently

### ISSUE THREAD

**Issue by Eeveelution** [Furball-Engine/Furball#29]
**Describe the bug**
[A clear and concise description of what the bug is.](https://github.com/Furball-Engine/Furball/blob/master/Furball.Engine/Engine/Graphics/Drawables/Managers/DrawableManager.cs#L16)

**Expected behavior**
do weak refrence pain

**Screenshots**
Iadfhbgdasghdagdafgdfgafdg

**Comment by Beyley** [comment]
Fixed in #049bc49a82379758dc93a1544b6d398e8a10d600
